### ISSUE TITLE
add Stata to the template

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#14]
@kobleary I think we have figured out how to add Stata in other projects since we created this template. Does that sound right to you?

If so, I'd like to add a Stata script to the workflow.

**Comment by SimonFreyaldenhoven** [comment]
@kobleary when you get a chance, can you let me know if you have any thoughts on [this](https://github.com/SimonFreyaldenhoven/example_template/issues/14#issuecomment-1583272294)?

**Comment by SimonFreyaldenhoven** [comment]
@kobleary thanks! your updated version works for me to, so happy to stick with this one.

I think the command points to whatever ```file.exe``` with the corresponding name here:
![image](https://github.com/SimonFreyaldenhoven/example_template/assets/20975521/77a0fdd5-279d-45e5-9de9-de9831efebb1)

In my case, I have both, but I think this is a bit installation dependent.

In the [Wiki](https://github.com/SimonFreyaldenhoven/example_template/wiki), I had previously noted this:
![image](https://github.com/SimonFreyaldenhoven/example_template/assets/20975521/be32fa4d-9ca1-4e11-a471-c005981d79da)

I will switch the roles of ```python``` and ```python3``` there.

If this all sounds good to you, I'll start a PR next

**Comment by SimonFreyaldenhoven** [comment]
continued in #20

**Comment by kobleary** [comment]
> @kobleary thanks! your updated version works for me to, so happy to stick with this one.
> 
> I think the command points to whatever `file.exe` with the corresponding name here: ![image](https://user-images.githubusercontent.com/20975521/247167246-77a0fdd5-279d-45e5-9de9-de9831efebb1.png)
> 
> In my case, I have both, but I think this is a bit installation dependent.
> 
> In the [Wiki](https://github.com/SimonFreyaldenhoven/example_template/wiki), I had previously noted this: ![image](https://user-images.githubusercontent.com/20975521/247167455-be32fa4d-9ca1-4e11-a471-c005981d79da.png)
> 
> I will switch the roles of `python` and `python3` there.
> 
> If this all sounds good to you, I'll start a PR next

Sounds good.
