### ISSUE TITLE
populate presentation

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#17]
@kobleary @nateschor Can you take a stab here at creating/editing existing figures for your presentation?

- [x] change the sample size to 1,000 in [500_8.csv](https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/simulation/designs/500_8.csv) (Nathan)
- [x] make axis labels larger and adjust the color and size of the plot in [create_plots.R](https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/plot/create_plots.R#L37-L42). See [ptol](https://jrnold.github.io/ggthemes/reference/ptol_pal.html) for potential colors (Ryan)
- [x] rerun pipeline from [main.py](https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/main.py) (Nathan)

**Comment by SimonFreyaldenhoven** [comment]
@nateschor Can we just replace the `500_8` specification with the new sample size instead of creating a third spec?

**Comment by kobleary** [comment]
> @kobleary is the correct way to run the pipeline:
> 
> 1. Create a new `.csv` file [here](https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/simulation/designs/500_8.csv) called `1000_10.csv`
> 2. Add 1000_10 to the 3rd line https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/designs_to_run.csv#L2
> 3. Run [main.py](https://github.com/SimonFreyaldenhoven/example_template/blob/aafd4e7590a302ea30bda24182d2442c59a2a9cf/analysis/source/main.py) without any arguments?
> 
> Thanks!

@nateschor Yep looks good!

**Comment by kobleary** [comment]
@nateschor Which one looks better?

| 16pt font | Default font |
|--------|--------|
| ![image](https://github.com/SimonFreyaldenhoven/example_template/assets/38228048/fcab83b9-d1b1-4f42-a1c1-620ca7c405fb) | ![image](https://github.com/SimonFreyaldenhoven/example_template/assets/38228048/1596387e-adc9-49a3-b23a-b8cf541b5c54)|

**Comment by nateschor** [comment]
@kobleary I think the 16pt font looks better, let's go with that one. Thanks!

**Comment by nateschor** [comment]
Thread continues in #19

**Comment by kobleary** [comment]
@SimonFreyaldenhoven fyi please do not actually merge #19

**Comment by nateschor** [comment]
## Summary

* changed the number of simulations from 500 to 1,000 (this should be a sufficiently large number of trials, see https://github.com/SimonFreyaldenhoven/example_template/pull/19#discussion_r1225632798)
* made the histogram axis titles [larger](https://github.com/SimonFreyaldenhoven/example_template/blob/41b1e65859d4d8b8c158f9063f53c68210669fe6/analysis/source/plot/create_plots.R#L33)
* switched the color to [cornflowerblue](https://github.com/SimonFreyaldenhoven/example_template/blob/41b1e65859d4d8b8c158f9063f53c68210669fe6/analysis/source/plot/create_plots.R#L40).
