### ISSUE TITLE
add Latex to template

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#21]
On this branch, I will add the compilation step to the template.

**Comment by SimonFreyaldenhoven** [comment]
@kobleary I added the compilation step to the pipeline. 

Running `main.py` now not only does all the analysis, but also recreates the updated pdf note. Could you see if running `main.py` works for you and do review here?

**Comment by SimonFreyaldenhoven** [comment]
continued in #22

**Comment by kobleary** [comment]
@SimonFreyaldenhoven This is a pretty cool feature! It looks like it tries to compile but I get this issue with the third figure (which isn't surprising I always get issues with LaTeX packages).  I'm going to update packages and retry. But I think you should be fine to merge.

![image](https://github.com/SimonFreyaldenhoven/example_template/assets/38228048/8bad6e5c-1285-4299-a6b4-d4ae14555bd0)
