### ISSUE TITLE
update figure 3

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#27]
@zumiko Welcome!

Could you please:

- [x] Read the wiki
- [x] Create a branch for this issue (You cn do so directly on the RHS of this post)
- [x] Look through the code to understand the repo setup (main.py under ```analysis/source``` is a good starting point)
- [x] Install the dependencies in the wiki and run ```main.py``` 
- [x] Confirm you can run the template (```analysis/output/time_log.txt``` should indicate a successful run)

After that
- [x] Can you change the color of Figure 3 in the draft to red? See below for the current version.
![image](https://github.com/SimonFreyaldenhoven/example_template/assets/20975521/8c13558c-4a7b-4230-a036-1d4b838e7435)

- [x]  Create a PR for your branch and assign @SimonFreyaldenhoven as a reviewer.

and of course, let me know if you have any questions!

**Comment by zumiko** [comment]
Actually maybe a little premature, realized that bibtex citation isn't appearing correctly, unless I run that program separately
