### ISSUE TITLE
Onboarding Jack

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#31]
@jackbunge1 Welcome! Before we get started, can you do the steps below? 

- [x] Read the wiki
- [x] Clone this repository to your machine
- [x] Look through the code to understand the repo setup (main.py under analysis/source is a good starting point)
- [x] Install the dependencies in the wiki and run main.py
- [x] Confirm you can run the template (analysis/output/time_log.txt should indicate a successful run)

Of course, let me know if you have any questions. Happy to find a time to sit down for a bit. I'm around today and pretty open.

**Comment by jackbunge1** [comment]
Hi Simon, 

I wanted to give you a quick update. I've had a bit of trouble installing the dependencies (access issues and don't have python installed). I've emailed IT and am waiting on a response; I'll let you know once this is resolved, and once I can run the template (or if other questions come up). Thanks

**Comment by SimonFreyaldenhoven** [comment]
@jackbunge1 sounds good! That was probably expected. Getting all software set up is non-trivial the first time. 

But once it's set up, it should be easy for future projects.

**Comment by SimonFreyaldenhoven** [comment]
As of now, we are waiting to figure out the Stata issue. Everything else runs.

**Comment by SimonFreyaldenhoven** [comment]
@jackbunge1 any update here?

**Comment by jackbunge1** [comment]
Hi Simon, thanks for checking in!

I've been able to install stata, and the main.py script now runs successfully. Here's a snapshot of the time_log.txt file:

![2024-09-03_11-53-26](https://github.com/user-attachments/assets/fabcacdf-be5a-4b35-98e3-ad1fb53a35e8)

Please let me know if there's anything else I can work on! Thank you

**Comment by SimonFreyaldenhoven** [comment]
@jackbunge1 perfect, thanks! I think we're all set here, unless you have any further git or coding questions.

**Comment by jackbunge1** [comment]
nope, I'm good for now! thank you very much for all of your help!
