### ISSUE TITLE
practice task Jack

### ISSUE THREAD

**Issue by SimonFreyaldenhoven** [SimonFreyaldenhoven/example_template#32]
@jackbunge1 Can you remind me again what software you'd like to use for this?

**Comment by jackbunge1** [comment]
do you happen to know what language Thorsten uses the most (/what you'll be using for the project)? otherwise, I'd prefer R

**Comment by SimonFreyaldenhoven** [comment]
@jackbunge1 not sure, I'm guessing Matlab (or perhaps Stata). But R works, let's start with that.

**Comment by jackbunge1** [comment]
ok sounds good, thanks

**Comment by SimonFreyaldenhoven** [comment]
- [ ] Create a branch for this issue (You can do so directly on the RHS of this post)

Working on this branch
- [ ] Add a function to [create_plots.R](https://github.com/SimonFreyaldenhoven/example_template/blob/03466672aea6e5d7bbee65445b1ac53460791563/analysis/source/plot/create_plots.R), called ```illustrate_LLN```. (LLN stands for Law of Large numbers)

This function should read the datasets under ```datastore```, and create a figure that has on the x-axis the number of rolls, and on the y-axis the number the Total sum/number of rolls up to that point. (Think of it at showing convergence of the average to the expected value). Does that make sense?

- [ ] Add a brief section to the tex note that uses the resulting figures.

**Comment by jackbunge1** [comment]
yep that makes sense. i'll let you know if I have any questions, thanks

**Comment by SimonFreyaldenhoven** [comment]
continued in #33
